# Generated by Django 4.0.4 on 2022-05-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_teacher_options_alter_comment_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Imgs')),
                ('bio', models.CharField(max_length=200)),
                ('pthone_number', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
